# 启动端口号
server:
  post: 8000

# MySQL数据源配置
mysql:
  username: root
  password: 123456
  url: tcp(localhost:3307)/imall?charset=utf8&parseTime=True&loc=Local

# 图片路径配置
upload:
  savePath: /Users/zchengo/Downloads/resource/images/
  accessUrl: http://localhost:8000/image/

# JWT配置
jwt:
  signingKey: z3d6k8v0n3w7m9sa1fd0u09h

# 定时任务
cron:
  enable: true

# 微信小程序配置
code2Session:
  appId: wxfe1490546ebc09bc
  appSecret: 8394c66a266b5d3952cceefc105d50fe

# 问题反馈配置
feedback:
  qqSmtp: smtp.qq.com
  qqEmail: 1933757688@qq.com
  qqEmailSecret: jjstmwtidhwhxhzc